param([Parameter(Mandatory=$true)][string]$Output)
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot
$destination=[IO.Path]::GetFullPath($Output)
if($destination.StartsWith($root.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase) -or $destination -eq $root){throw 'Export outside the working installation.'}
if(Test-Path -LiteralPath $destination){throw 'Choose a new, empty destination path; existing folders are never overwritten.'}
New-Item -ItemType Directory -Path $destination | Out-Null
foreach($file in Get-ChildItem -LiteralPath $root -File -Recurse){
 $relative=$file.FullName.Substring($root.Length+1)
 if($relative -match '^(state|backup|\.git|\.codex|outputs|original_desktop)\\' -or $file.Extension -in @('.log','.zip') -or $file.Name -like 'A-Shell-Setup.exe*' -or $relative -eq 'assets\package-manifest.json'){continue}
 $target=Join-Path $destination $relative
 New-Item -ItemType Directory -Path (Split-Path $target) -Force | Out-Null
 Copy-Item -LiteralPath $file.FullName -Destination $target
}
# Recipient setup discovers its own installed-app paths and shortcut IDs.
$path=Join-Path $destination 'assets\icon-map.json'
$mapping=Get-Content -LiteralPath $path -Raw|ConvertFrom-Json
foreach($app in $mapping.apps){$app.appIds=@($app.appIds|Where-Object {$_ -notmatch '^(?:[A-Za-z]:\\|\\\\|Microsoft\.AutoGenerated\.)' -and $_ -notmatch 'S-1-5-21-'})}
$mapping.apps=@($mapping.apps|Where-Object {@($_.appIds).Count})
$mapping|ConvertTo-Json -Depth 15|Set-Content -LiteralPath $path -Encoding UTF8
$temp=Join-Path ([IO.Path]::GetTempPath()) ('AShell-export-'+[guid]::NewGuid().ToString('N')+'.zip')
try {& (Join-Path $destination 'scripts\Build-Package.ps1') -Output $temp}
finally {if(Test-Path -LiteralPath $temp){Remove-Item -LiteralPath $temp}}
Write-Output "[OK] GitHub copy prepared: $destination. Personal backups, logs and machine-specific app IDs excluded."
